{
  "openapi": "3.0.0",
  "info": {
    "title": "Squidex API",
    "description": "# Introduction\n\nThe API provides two specifications. The Content API usually returns one object per schema field where the keys are the languages (or `iv` for non-localized) fields and the values are the actual field values.\n\nYou can use the `X-Flatten` header to return a flat structure when you query content items. This is more performant and easier for code generation. Unfortunantely it cannot be modelled with OpenAPI. Therefore we provide two different documents for yo[...]",
    "version": "7.0.0.0",
    "x-logo": {
      "url": "https://cloud.squidex.io/images/logo-white.png",
      "backgroundStyle": "",
      "backgroundColor": "#3f83df"
    }
  },
  "servers": [
    {
      "url": "https://cloud.squidex.io"
    }
  ],
  "paths": {
    "/api/content/kalleportfolio/projetos/": {
      "get": {
        "tags": [
          "Projetos"
        ],
        "summary": "Query 'Projetos' contents items.",
        "description": "How to make queries?\n\nRead more about it at: https://docs.squidex.io/04-guides/02-api.html\n\nThe query endpoints support three options:\n\n### Query with OData\n\nSquidex supports a subset of the OData (https://www.odata.org/) syntax with with the following query options:\n\n* **$top**: The $top query option requests the number of items in the queried collection to be included in the result. The default value is 20 and the maximum allowed value is 200. You can change t[...]",
        "operationId": "QueryProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.read.own"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Projetos"
        ],
        "summary": "Create a 'Projetos' content item.",
        "operationId": "CreateProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.create"
            ]
          }
        ]
      }
    },
    "/api/content/kalleportfolio/projetos/query": {
      "post": {
        "tags": [
          "Projetos"
        ],
        "summary": "Query 'Projetos' contents items using Post.",
        "operationId": "QueryPostProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.read.own"
            ]
          }
        ]
      }
    },
    "/api/content/kalleportfolio/projetos/{id}": {
      "get": {
        "tags": [
          "Projetos"
        ],
        "summary": "Get a 'Projetos' content item.",
        "operationId": "GetProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.read.own"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Projetos"
        ],
        "summary": "Upsert a 'Projetos' content item.",
        "operationId": "UpsertProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.upsert"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Projetos"
        ],
        "summary": "Update a 'Projetos' content item.",
        "operationId": "UpdateProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.update.own"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Projetos"
        ],
        "summary": "Patch a 'Projetos' content item.",
        "operationId": "PatchProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.update.own"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Projetos"
        ],
        "summary": "Delete a 'Projetos' content item.",
        "operationId": "DeleteProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.delete.own"
            ]
          }
        ]
      }
    },
    "/api/content/kalleportfolio/projetos/{id}/{version}": {
      "get": {
        "tags": [
          "Projetos"
        ],
        "summary": "Get a 'Projetos' content item by id and version.",
        "operationId": "GetVersionedProjetosContent",
        "deprecated": true,
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.read.own"
            ]
          }
        ]
      }
    },
    "/api/content/kalleportfolio/projetos/{id}/validity": {
      "get": {
        "tags": [
          "Projetos"
        ],
        "summary": "Validates a 'Projetos' content item.",
        "operationId": "ValidateProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.read.own"
            ]
          }
        ]
      }
    },
    "/api/content/kalleportfolio/projetos/bulk": {
      "post": {
        "tags": [
          "Projetos"
        ],
        "summary": "Bulk update content items.",
        "operationId": "BulkProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.read.own"
            ]
          }
        ]
      }
    },
    "/api/content/kalleportfolio/projetos/{id}/status": {
      "put": {
        "tags": [
          "Projetos"
        ],
        "summary": "Change the status of a 'Projetos' content item.",
        "operationId": "ChangeProjetosContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.projetos.changestatus.own"
            ]
          }
        ]
      }
    },
    "/api/content/kalleportfolio/": {
      "get": {
        "tags": [
          "__Shared"
        ],
        "summary": "Query contents across all schemas.",
        "operationId": "Query__SharedContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.__Shared.read.own"
            ]
          }
        ]
      }
    },
    "/api/content/kalleportfolio/bulk": {
      "post": {
        "tags": [
          "__Shared"
        ],
        "summary": "Bulk update content items across all schemas.",
        "operationId": "Bulk__SharedContent",
        "security": [
          {
            "squidex-oauth-auth": [
              "squidex.apps.kalleportfolio.contents.__Shared.read.own"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "squidex-oauth-auth": {
        "type": "openIdConnect",
        "description": "Squidex uses OpenId Connect (OIDC) with the Client Credentials Flow (defined in OAuth 2.0 RFC 6749, section 4.4).\n\nThe OpenId Connect Client Credentials flow can be used for machine to machine authentication. In this grant a specific user is not authorized but rather the credentials are verified and a generic `access_token` is returned.\n\nThe `access_token` is a signed JSON Web Token (JWT) which contains expiry information. \n\nTo retrieve an access token you must pass[...]",
        "openIdConnectUrl": "https://cloud.squidex.io/identity-server/.well-known/openid-configuration"
      }
    }
  },
  "security": [
    {
      "squidex-oauth-auth": [
        "squidex-api"
      ]
    }
  ],
  "tags": [
    {
      "name": "Projetos",
      "description": "API endpoints for 'Projetos' content items."
    },
    {
      "name": "__Shared",
      "description": "API endpoints for operations across all schemas."
    }
  ]
}